export const CONSTANT_NEW = 'FILTER_NEW';
export const CONSTANT_OLD = 'FILTER_OLD';
export const CONSTANT_TRAVEL = 'FILTER_TRAVEL';
export const CONSTANT_PETS = 'FILTER_PETS';
export const CONSTANT_HOME = 'FILTER_HOME';
export const CONSTANT_MISC = 'FILTER_MISC';
export const ACTION_TYPE_FILTER = 'ACTION_TYPE_FILTER';